### ISSUE TITLE
Feature request: CSS Preprocessor Support

### ISSUE THREAD

**Issue by Scotchester** [topcoat/topdoc#23]
It might be nice for topdoc to output the preprocessed code snippets (e.g., LESS, Sass) instead of just CSS.

**Comment by zeropaper** [comment]
I believe that this should **not** be done.

You can always compile your less/sass/stylus and keep comments in the CSS and then run topdoc before minification.

**Comment by GarthDB** [comment]
@zeropaper I think that should be the plan moving forward. The current 1.0.0-beta is using postcss to parse out the comments. It could be possible to use a different parser with postcss like the [postcss-scss parser](https://github.com/postcss/postcss-scss). If we did go with a solution like that this would be the way to go.
