### ISSUE TITLE
Nested comments cause usage guides generation failure.

### ISSUE THREAD

**Issue by elycruz** [topcoat/topdoc#24]
Docs are not generated if there is a topdoc comment nested within a selector css definition;  I.e., 

```
.selector {
  /* topdoc
    name: ...
    ...
  */
}
```

This commonly happens when using css pre-processors that allow to include module code within other modules:

```
// Sass/Scss
.selector {
  @import "other-module";
}
```

We should allow these kind of comments to be parsed by the topdoc tool.

**Comment by GarthDB** [comment]
@elycruz I just switched to using postcss for parsing the topdoc comments - I'll add this use case to the tests and see if it is already fixed in this new architecture.

**Comment by GarthDB** [comment]
@elycruz reviewing this, it actually isn't recommended since Topdoc uses the location of the comments to split up the css into components.

**Comment by elycruz** [comment]
Awesome, gotcha
