### ISSUE TITLE
Only the first iframe is generated

### ISSUE THREAD

**Issue by Couto** [topcoat/topdoc#28]
If I have a stylesheet where two components use the `iframe:true` parameter, only the first one will be rendered into a separate HTML file to be used inside an iframe.

I'm unsure if this is a `topdoc` problem or the theme that I'm using, since `topdoc` requires a template. 

I'm using the [topdoc-theme](https://github.com/topcoat/topdoc-theme) as the template to achieve some output.

However this is a required featured to avoid style bleeding issues like [#13](https://github.com/topcoat/topdoc-theme/issues/13)

**Comment by GarthDB** [comment]
In the upcoming release (1.0.x) support from generating iframes has been removed and instead should be done in a custom template.
