### ISSUE TITLE
Colon inside markup

### ISSUE THREAD

**Issue by peebeebee** [topcoat/topdoc#30]
It would be nice if you could add inline styles to your markup documentation.
Ex.:

```
<div class="special-class" style="width: 100%;">Special class full width example</div>
<div class="special-class" style="width: 50%;">Special class half width example</div>
```

Right now it fails on the colon inside the style attribute. I _guess_ it has to do with the regex that is used in the parsing?

**Comment by GarthDB** [comment]
Fixed in the new postcss-topdoc version of topdoc (currently a `beta` tagged release). You'll need to use the correct yaml multiline syntax:
