### ISSUE TITLE
Feature Request: Ability to specify individual source files, rather than a directory

### ISSUE THREAD

**Issue by matt-bailey** [topcoat/topdoc#32]
And/or, the ability to 'negate' files.

For example, let's say in my `styles` directory I have three files, `critical.css`,  `main.css` and `components.css`. I might only want to build the docs from `components.css` and not the other two files.

By the way, I'm using the Grunt plugin. It would be great if it followed the standard file object and globbing spec: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by GarthDB** [comment]
@matt-bailey the new beta is using [glob](https://github.com/isaacs/node-glob) to match what files you want.

You can install and try it out using the 'beta' tag:

```sh
$ npm install --save topdoc@beta
```
