### ISSUE TITLE
topdoc (postcss) should copy template dependencies

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc#37]
Per conversation with @GarthDB, topdoc should assume dependencies in the template should be copied to the docs destination.  The glob would be something like:

```
['template-dir/**/*', '!*.pug']
```

Not sure what else I'm forgetting... but it's probably something.

**Comment by GarthDB** [comment]
Fixed in the beta.

**Comment by misterbrownlee** [comment]
Thanks, it is working great.
