### ISSUE TITLE
topdoc (postcss) can't find index.pug

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc#38]
It's either a missing feature or a bug, but topdoc should be able to take a path to just the directory and sort it out from there.  If there is no index.js, it could all back to an index.pug and work it out.

... or maybe that's a bad assumption. Will discuss with @GarthDB

**Comment by misterbrownlee** [comment]
I can take a crack at this if you want to assign to me?  Just LMK.

**Comment by GarthDB** [comment]
This is fixed in the beta

**Comment by misterbrownlee** [comment]
IT'S ALIVE!!!
