### ISSUE TITLE
topdoc @ 1.0.5 not finding 'assetDirectory' for copy

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc#42]
Using 1.0.5, we've stopped getting assets copied over.

💥  goes our docs 💀

**Comment by GarthDB** [comment]
Is it still working in one of the previous versions?

Could you paste the script command you are using and any config (rc file, etc)?

**Comment by misterbrownlee** [comment]
Oh random I somehow made a #44 which is a duplicate, I'll close that.

In 1.0.3 this worked:
```
{
  "source": "dist/reference/css",
  "destination": "dist/reference/docs",
  "clobber": true,
  "assetDirectory": "docs-template",
  "pugFile": "docs-template/template.pug"
}
```
