### ISSUE TITLE
v1.0.5 creating `node_modules` in output directory

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc#45]
There is now a `node_modules` folder in the output directory, as well as an `.npmignore` file.  I didn't notice that with 1.0.3? I could roll back to verify.  But yeah.

**Comment by GarthDB** [comment]
I'll look into that most likely it's the ignore asset field causing all of these issues.

**Comment by misterbrownlee** [comment]
ok... lmk if you want me to pick it up?  I could take a look as well.

**Comment by GarthDB** [comment]
fixed in v1.0.8 beta
