### ISSUE TITLE
The ":" came back

### ISSUE THREAD

**Issue by misterbrownlee** [topcoat/topdoc#46]
In the output pass when the source css gets copied to dest a ":" get's added in the dest folder.

**Comment by misterbrownlee** [comment]
Turns out it was in topdoc-default-theme, so closing this because we [fixed it there](https://github.com/topcoat/topdoc-default-template/pull/2).

**Comment by GarthDB** [comment]
@misterbrownlee I just published v1.0.6 (beta) with the updated dependency included.
